# docker-compose.yml
version: '3.9'

services:
  orchestrator:
    build: ./orchestrator
    ports:
      - "8000:8000"
    environment:
      - LM_API_URL=http://host.docker.internal:1234
      - MODEL_NAME=qwen3-8b